### ISSUE TITLE
TalkBox Does Not Play Audio

### ISSUE THREAD

**Issue by allenkaplan** [ryang-123/EECS2311-Project#1]
Version - Midterm Release
Component - Simulator
Platform - Surface Book 2, Windows 10
Java Version - Java 8, Update 191

I set the configuration for one button with an image and an audio file. When attempting to play the audio with a left mouse click file in the simulator, no audio plays. The image is still displayed.

Image: Perplexed, Sound: ALL .wavs

![image](https://user-images.githubusercontent.com/25397434/54139302-a07c6200-43f7-11e9-9ec2-aeffaa055e59.png)

![image](https://user-images.githubusercontent.com/25397434/54139257-88a4de00-43f7-11e9-8509-932fdc924cee.png)

**Comment by ryang-123** [comment]
SUMMARY:Issue was case specific and external (user's system). 

Upon running the configuration and simulator frame in the debugger, no errors or outlier anomalies occurred and everything ran as expected. Testing it once more on the issuer's device with the exact settings determined the issue to have resulted due to client error. The client had not had their sound settings configured so the bug they believed to occur was just a mishap. Bug officially closed.
